syntax = "proto3";

package websocket;

import "google/protobuf/timestamp.proto";

message PbVector2 {
  double x = 1;
  double y = 2;
}

message ClientToServerMessage {
  oneof payload {
    // Lobby messages
    StartGameMessage start_game = 1;

    // Game messages
    PositionUpdateMessage position_update = 2;
    InventoryUpdateMessage inventory_update = 3;
  }
}

message StartGameMessage {
}

message PositionUpdateMessage {
  PbVector2 position = 1;
}

message InventoryUpdateMessage {
  string item_id = 1; // empty string if no item is held
}

message ServerToClientMessage {
  oneof payload {
    LobbyUpdatedMessage lobby_updated = 1;
    GameStartedMessage game_started = 2;
  }
}

message LobbyUpdatedMessage {
  string room_code = 1;
  repeated string player_names = 2;
  bool is_host = 3;
}

message GameStartedMessage {
  PlayerRole role = 1;
  google.protobuf.Timestamp end_time = 2;
  PbVector2 initial_position = 3;
  string held_item_id = 4; // empty string if no item is held
}

enum PlayerRole {
  PLAYER_ROLE_UNSPECIFIED = 0;
  PLAYER_ROLE_COOK = 1;
  PLAYER_ROLE_INSTRUCTOR = 2;
}
